/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesRemodelingRouteImport } from './routes/services.remodeling'
import { Route as ServicesPoolsRouteImport } from './routes/services.pools'
import { Route as ServicesDecksRouteImport } from './routes/services.decks'
import { Route as ServicesAFrameRouteImport } from './routes/services.a-frame'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRemodelingRoute = ServicesRemodelingRouteImport.update({
  id: '/remodeling',
  path: '/remodeling',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPoolsRoute = ServicesPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDecksRoute = ServicesDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAFrameRoute = ServicesAFrameRouteImport.update({
  id: '/a-frame',
  path: '/a-frame',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/services/a-frame': typeof ServicesAFrameRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/pools': typeof ServicesPoolsRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/service-area': typeof ServiceAreaRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/a-frame': typeof ServicesAFrameRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/pools': typeof ServicesPoolsRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/services/a-frame': typeof ServicesAFrameRoute
  '/services/decks': typeof ServicesDecksRoute
  '/services/pools': typeof ServicesPoolsRoute
  '/services/remodeling': typeof ServicesRemodelingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/portfolio'
    | '/service-area'
    | '/services'
    | '/testimonials'
    | '/services/a-frame'
    | '/services/decks'
    | '/services/pools'
    | '/services/remodeling'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/portfolio'
    | '/service-area'
    | '/testimonials'
    | '/services/a-frame'
    | '/services/decks'
    | '/services/pools'
    | '/services/remodeling'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/portfolio'
    | '/service-area'
    | '/services'
    | '/testimonials'
    | '/services/a-frame'
    | '/services/decks'
    | '/services/pools'
    | '/services/remodeling'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PortfolioRoute: typeof PortfolioRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/remodeling': {
      id: '/services/remodeling'
      path: '/remodeling'
      fullPath: '/services/remodeling'
      preLoaderRoute: typeof ServicesRemodelingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/pools': {
      id: '/services/pools'
      path: '/pools'
      fullPath: '/services/pools'
      preLoaderRoute: typeof ServicesPoolsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/decks': {
      id: '/services/decks'
      path: '/decks'
      fullPath: '/services/decks'
      preLoaderRoute: typeof ServicesDecksRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/a-frame': {
      id: '/services/a-frame'
      path: '/a-frame'
      fullPath: '/services/a-frame'
      preLoaderRoute: typeof ServicesAFrameRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAFrameRoute: typeof ServicesAFrameRoute
  ServicesDecksRoute: typeof ServicesDecksRoute
  ServicesPoolsRoute: typeof ServicesPoolsRoute
  ServicesRemodelingRoute: typeof ServicesRemodelingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAFrameRoute: ServicesAFrameRoute,
  ServicesDecksRoute: ServicesDecksRoute,
  ServicesPoolsRoute: ServicesPoolsRoute,
  ServicesRemodelingRoute: ServicesRemodelingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PortfolioRoute: PortfolioRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
